[tox]
envlist = py312
skipsdist = True

[testenv]
deps =
    -r requirements-dev.txt
setenv =
    COVERAGE_PROCESS_START = {toxinidir}/tox.ini
    COVERAGE_FILE = {toxworkdir}/.coverage
    PYTHONPATH = {toxinidir}/scripts/cov_init{:}{toxinidir}
commands =
    python scripts/run_coverage_workflow.py

[coverage:run]
source = commuted_calligraphy
relative_files = True
parallel = True
branch = True

[coverage:report]
show_missing = True
skip_covered = False
