[tox]
envlist = py312
skipsdist = True

[testenv]
deps =
    -r requirements-dev.txt
    pytest-cov
setenv =
    COVERAGE_PROCESS_START = {toxinidir}/tox.ini
commands =
    pytest --cov=commuted_calligraphy --cov-config=tox.ini --cov-branch --cov-report= --junitxml=test-results.xml
    python -c "import glob, subprocess, sys; sys.exit(subprocess.call([sys.executable, '-m', 'coverage', 'combine']) if glob.glob('.coverage.*') else 0)"
    python -m coverage xml -o coverage.xml
    python -m coverage report -m

[coverage:run]
relative_files = True
parallel = True
patch = subprocess

[coverage:report]
show_missing = True
skip_covered = False
